language: node_js

jobs:
  include:
    - node_js: stable
      name: Test on stable Node.js
      script: npm run test:mocha
    - node_js: 12
      name: Test on Node.js 12
      script: npm run test:mocha
    - node_js: 10
      name: Test on Node.js 10
      script: npm run test:mocha
    - node_js: 12
      name: Check code style
      script: npm run test:lint
